[mgr]
show_hidden = true

[opener]
edit = [
    { run = '${EDITOR} "$1"', desc = "Default Editor", block = true, for = "linux" },
    { run = 'xdg-open "$1"', desc = "Open (XDG-Mime)", block = true, for = "linux" },
    { run = 'code "$1"', desc = "VSCode", block = true, for = "linux" },
]


open = [
    { run = 'xdg-open "$1"', desc = "Open", for = "linux" }
]